### ISSUE TITLE
主链同步的时候，经常报err=ErrHeightNotExist，导致同步特别缓慢

### ISSUE THREAD

**Issue by cjango** [bityuan/bityuan#122]
t=2021-09-01T09:06:17+0800 lvl=info msg=ReadBlockToExec:ReadBlockByHeight module=blockchain submodule=syn height=12349053 peerMaxBlkHeight=15974489 err=ErrHeightNotExist
t=2021-09-01T09:06:17+0800 lvl=eror msg=refreshPeerInfo module=p2p.peer new stream error="protocol not supported" peer id=16Uiu2HAmN1N9ghaVGKrzxxSzSZ2tcv1VcJJKFuehsjLLydF8A2Gu
t=2021-09-01T09:06:17+0800 lvl=eror msg=refreshPeerInfo module=p2p.peer error="protocol not supported" pid=16Uiu2HAmN1N9ghaVGKrzxxSzSZ2tcv1VcJJKFuehsjLLydF8A2Gu
t=2021-09-01T09:06:18+0800 lvl=info msg=ReadBlockToExec:ReadBlockByHeight module=blockchain submodule=syn height=12349053 peerMaxBlkHeight=15974489 err=ErrHeightNotExist

**Comment by baramguli** [comment]
Hello,
I have question, about bityuan. 
Can you answer please: 
1) what is max supply of bityuan?
2) what is Speed of transaction per second? 
3)  what is transaction Price? 
In i have bityuan White papper ( maybe old) 
And it's written correctly supply 320 mIllion ( Page 14) but, on bityuan website corrently supply is 512 million. 
I would like to invest but can't find some exact information.
Thanks for your project and best wishes bityuan team from Finland.
