### ISSUE TITLE
1.67.0同步节点卡到546820高度

### ISSUE THREAD

**Issue by cjango** [bityuan/bityuan#155]
INFO[03-28|19:52:21] dbMaybeStoreBlock block header existed   module=blockchain hash=0x2f4aed8177ff31a90b2c61e3353014f8167e0a4bdf03609c98da924aa4dd440b
INFO[03-28|19:52:21] PreExecBlock                             module=util height=546820 checkCount=3 CheckSign=503.917µs
EROR[03-28|19:52:21] exec tx error =                          module=execs err=ErrInvalidEthAddr exec=coins action=transfer
EROR[03-28|19:52:21] exec tx =                                module=execs index=2 execer=coins err=ErrInvalidEthAddr
INFO[03-28|19:52:21] PreExecBlock                             module=util height=546820 ExecTx=651.613µs
INFO[03-28|19:52:21] PreExecBlock                             module=util height=546820 WaitDupCheck=184ns
INFO[03-28|19:52:21] ExecBlock                                module=util height=546820 ntx=3 writebatchsync=false cost=2.227301ms
EROR[03-28|19:52:21] connectBlock ExecBlock is err!           module=blockchain height=546820 err=ErrCheckStateHash
EROR[03-28|19:52:21] ReadBlockToExec:ProcessBlock:err!        module=blockchain submodule=syn height=546820 hash=0x2f4aed8177ff31a90b2c61e3353014f8167e0a4bdf03609c98da924aa4dd440b err=ErrCheckStateHash

**Comment by bysomeone** [comment]
1.67.1已修复
