### ISSUE TITLE
启动裁剪的配置文件进行同步时，存在内存溢出

### ISSUE THREAD

**Issue by xies1031** [bityuan/bityuan#9]
启动裁剪的配置文件进行同步时，存在内存溢出，导致chain33崩溃
![image](https://user-images.githubusercontent.com/44956625/50073113-85dc8780-0212-11e9-9454-8ee3fb40d081.png)

**Comment by lyh169** [comment]
大概测试了下，主要是go的垃圾回收不能很快将协程中的内存给释放掉（协程是只进一次的），还有一些就是以内存换磁盘的一些处理，还有就是一些关于效率上面的考虑调大一些参数，这个我在想想优化下代码，我们这边大概 要比特元运行的配置是多少的，如内存等？  @vipwzw   @xies1031

**Comment by lyh169** [comment]
目前 内存 基本在1G内，可能有峰值超过1G
